name: New
on: push

env:
  RELEASE: 2022.06.01.1140

jobs:

  build1:
#     runs-on: ubuntu-latest
    runs-on: [ self-hosted, runner1 ]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: create branch
        run:  git checkout -b ${{ env.RELEASE }}
      - name: Run a one-line script
        run:  |
          echo "build1" > test.txt
          echo "build1" > test2.txt
          date >> test.txt
          date >> test2.txt
      - name: Commit files in branch
        run: |
          git config --local user.email "sujaikumar@gmail.com"
          git config --local user.name "sujaikumar"
          git add -A
          git commit -m "Add changes from build1"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE }}

  build2:
#     runs-on: ubuntu-latest
    runs-on: [ self-hosted, runner2 ]
    needs: build1

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ env.RELEASE }}
      - name: Run a one-line script
        run:  |
          echo "build2" >> test.txt
          date >> test.txt
      - name: Commit files in branch
        run: |
          git config --local user.email "sujaikumar@gmail.com"
          git config --local user.name "sujaikumar"
          git add -A
          git commit -m "Add changes from build2"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE }}
