name: New
on: workflow_dispatch

env:
  RELEASE: 2022.06.01.1106

jobs:

  build1:
    runs-on: ubuntu-latest
#     runs-on: [ self-hosted, runner1 ]

    steps:
      - uses: actions/checkout@v3
      - name: create branch
        run:  git checkout -b ${{ env.RELEASE }}
      - name: Run a one-line script
        run:  |
          echo "build1" > test.txt
          date >> test.txt
      - name: Commit files in branch
        run: |
          git config --local user.email "sujaikumar@gmail.com"
          git config --local user.name "sujaikumar"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.RELEASE }}

  build2:
    runs-on: ubuntu-latest
#     runs-on: [ self-hosted, runner2 ]
    needs: build1

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE }}
      - name: Run a one-line script
        run:  |
          echo "build2" >> test.txt
          date >> test.txt
      - name: Commit files in branch
        run: |
          git config --local user.email "sujaikumar@gmail.com"
          git config --local user.name "sujaikumar"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.RELEASE }}
